#Web服务器端口
server:
  port: ${ApplicationCenter.port}

#当前环境
eureka:
  environment: ${spring.profiles.active}
  server:
    enable-self-preservation: false #允许自我保护
    eviction-interval-timer-in-ms: 30000 #清理周期
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: ${ApplicationCenter.url}
  instance:
    lease-renewal-interval-in-seconds: 30 # 续约更新时间间隔
    lease-expiration-duration-in-seconds: 90 # 续约到期时间
#    prefer-ip-address: true #注册使用ip
#    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例id
#    ip-address: 127.0.0.1 #可访问的ip地址


#调试或者输出日志
logging:
  file: logs/${project.artifactId}.log
#debug: true


