#Web服务器端口
server:
  port: ${ApplicationCenter.port}

#当前环境
eureka:
  environment: ${spring.profiles.active}
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: ${ApplicationCenter.url}


