spring:
                 cloud:
                   stream:
                     kafka:
                       binder:
                         brokers: 192.168.1.248:9092

                   #允许消息总线
                   bus:
                     enabled: true