version: '3.1'

services:
  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${es_version}"
    container_name: es01
    restart: always
    hostname: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${store}/data1:/usr/share/elasticsearch/data
      - ${store}/ik:/usr/share/elasticsearch/plugins/ik
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  es02:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${es_version}"
    container_name: es02
    restart: always
    hostname: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${store}/data2:/usr/share/elasticsearch/data
      - ${store}/ik:/usr/share/elasticsearch/plugins/ik
    ports:
      - 6200:9200
      - 6300:9300
    networks:
      - esnet

  kibana:
    image: "docker.elastic.co/kibana/kibana:${es_version}"
    container_name: kibana
    restart: always
    hostname: kibana
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: ${kibana_host}
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - esnet

networks:
  esnet:
 


#安装shell的依赖 centos
# yum install -y dos2unix wget curl unzip ; ;source .env ; mkdir -p  ${store}


#修改MaxMap
#vim /etc/sysctl.conf
#vm.max_map_count=262144
#sysctl -w vm.max_map_count=655360
#sysctl -a | grep "vm.max_map_count"


#中文分词库
#wget -O elasticsearch-analysis-ik-${es_version}.zip https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v${es_version}/elasticsearch-analysis-ik-${es_version}.zip ; unzip -d $store/ik elasticsearch-analysis-ik-${es_version}.zip ; rm -rf elasticsearch-analysis-ik-${es_version}.zip



#防火墙
#sudo firewall-cmd --add-port=6200/tcp --permanent
#sudo firewall-cmd --add-port=6300/tcp --permanent
#sudo firewall-cmd --add-port=9200/tcp --permanent
#sudo firewall-cmd --add-port=9300/tcp --permanent
#sudo firewall-cmd --add-port=5601/tcp --permanent
#firewall-cmd --reload


#创建挂载数据
#mkdir -p ${store}/data1 ; mkdir -p ${store}/data2 
#chmod -R 777 ${store}


#启动
#docker-compose up -d

#查看进度
#curl http://127.0.0.1:9200/_cat/health


#访问kibana

