version: '3.1'

services:
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    volumes:
      - /opt/redis:/data
    command: redis-server
    ports:
      - 6379:6379