version: '3.1'

services:
  zipkin_mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: zipkin_mysql
#    ports:
#      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${store}:/var/lib/mysql
      - ./init_data.sh:/tmp/data/init_data.sh
      - ./mysql.sql:/tmp/data/init_zipkin.sql
      - .env:/tmp/data/.env


  zipkin:
    image: openzipkin/zipkin
    restart: always
    hostname: zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    environment:
      STORAGE_TYPE: mysql
      MYSQL_HOST: zipkin_mysql
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}


