version: '3.1'

services:
  zipkin_es:
    image: elasticsearch
    restart: always
    hostname: zipkin_es
    container_name: zipkin_es
    volumes:
      - "/opt/zipkin/es:/usr/share/elasticsearch/data"
  zipkin:
    image: openzipkin/zipkin
    restart: always
    hostname: zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    environment:
      ES_HOSTS: "zipkin_es"
      STORAGE_TYPE: "elasticsearch"

  # docker run --name elasticsearch -d -p 9200:9200 -p 9300:9300  -v /opt/es:/usr/share/elasticsearch/data elasticsearch

  # docker run --name zipkin --link elasticsearch:elasticsearch -d -p 9411:9411 -e STORAGE_TYPE=elasticsearch -e ES_HOSTS=elasticsearch openzipkin/zipkin