package com.fast.dev.pay.server.core.cpcn.param;

import lombok.Data;

@Data
public class Item {
    private String itemNo;
    private String batchNo;
    private String serialNumber;
    private String txTime;
    private long amount;
    private int accountType;
    private String accountName;
    private String accountNumber;
    private String branchName;
    private String province;
    private String city;
    private String note;
    private String paymentAccountNumber;
    private String balance;
    private String freeze;
    private String phoneNumber;
    private String email;
    private String identificationType;
    private String identificationNumber;
    private String bankID;
    private int status;
    private String bankTxTime;
    private String responseCode;
    private String responseMessage;
    private String cardMediaType;
    private String bankNoByPBC;
    private String registerNo;
    private String SettlementAmount;
    private String SettlementUsage;
    private String SourceInstitutionID;
    private String SourceTxSN;
    private String SourceTxType;
    private String institutionID;
    private String institutionName;
    private String institutionShortName;
    private String settlementFlag;
    private String relatedTxSNBinding;
    private String txSNBinding;
    private String txSn;
    private String txType;
    private String operation;
    private String receivableAmount;
    private String frozenAmount;
    private String remark;
    private String sourceTxCode;
    private String orderNo;
    private String txDate;
    private String receivable;
    private String frozen;
    private String txSN;
    private String paymentFlag;
    private String bankResponseCode;
    private String bankResponseMessage;
    private String rowType;
    private String goodZxNo;
    private String preferType;
    private String taxRateType;
    private String taxSpecialManage;
    private String goodsNo;
    private String commodityName;
    private String specificationModel;
    private String unit;
    private String quantity;
    private String unitPrice;
    private String taxRate;
    private String tax;
    public Object Long;
}
