eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    #    instance-id: 192.168.8.51:${GetWayCenter.port} #实例id
    #    ip-address: 192.168.8.51 #可访问的ip地址
    instance-id: 192.168.0.37:${GetWayCenter.port} #实例id
    ip-address: 192.168.0.37 #可访问的ip地址



#允许端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"




limit:
  roles:
    firewall:
      url: "/ucenter/*"
      policy:
        cycleTime: 10
        accessCount: 10
        blockTime: 60
    service:
      url: "/applicationserver/*,/configserver/*,/gatewayserver/*,/gatewaycenter/*,/pushserver/*"
    manager:
      url: "*/manager/*,*/endpoints/*"
      allowIp: "127.0.0.1"
    openapi:
      url: "*/openapi/*"
      exclusion: "/openapi/*"



spring:
  redis:
    host: 192.168.8.52
    port: 6379
    database: 6


logging:
  file:
    name: logs/${project.artifactId}.log
  level:
    com:
      fast:
        dev:
          gateway:
            core: debug
#debug: true
#trace: true