#设置可访问的ip
eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 192.168.8.51:${server.port} #实例id
    ip-address: 192.168.8.51
    #可访问的ip地址



spring:
  data:
    mongodb:
      uri: mongodb://timercenter:timercenter@192.168.8.52:27017,192.168.8.52:27018,192.168.8.52:27019,192.168.8.52:27020/timercenter?replicaSet=MongoSets
      auto-index-creation: true
#      database: timercenter
#      host: 192.168.8.52:27017
#      username: timercenter
#      password: timercenter


timer:
  task:
    process:
      maxExecuteTaskCount: 5
    default:
      http:
        url: http://www.baidu.com



logging:
#  level:
#    org:
#      springframework:
#        web:
#          servlet:
#            DispatcherServlet: DEBUG
#        cloud:
#          sleuth: DEBUG
    com:
      fast:
        dev:
          data:
            mongo: DEBUG