#默认端口号
server:
  port: ${UserCenter.port}
  servlet:
    context-path: ${UserCenter.context.path}


#注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${ApplicationCenter.url}




#允许消息总线
spring:
  cloud:
    stream:
      bindings:
        UserCenterInputStream:
          group: "UserCenterStream"
        UserCenterOuputStream:
          group: "UserCenterStream"
          destination: "UserCenterInputStream"
      #kafka
      kafka:
        binder:
          brokers: ${Kafka.brokers}
    bus:
      enabled: true


#允许端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"




  #开启断路器
  #feign.hystrix.enabled=true


  #测试代码，后面移动到配置中心里




ucenter:
  validate:
    app:
      demo1:
        debug: true
        serviceTokenTimeOut: 300000
        maxCanAccessCount: 5
        rule:
          Sms:
            length: 4
            scope: Number
            extraCharset: ""
          Image:
            length: 4
            scope: Charset
            extraCharset: ""