#设置可访问的ip
eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 192.168.8.15:${server.port} #实例id
    ip-address: 192.168.8.15 #可访问的ip地址



spring:
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
  data:
    mongodb:
      database: ucenter
      host: 192.168.8.12:27017
#      username:
#      password:
  redis:
    host: 192.168.8.12
    port: 6379
    database: 1



#配置
kaptcha:
  width: 100
  height: 41
  fontColor: "red"
  fontNames: "宋体,楷体,微软雅黑"


ucenter:
  validate:
    #全局配置
    debug: true
    serviceTokenTimeOut: 300000
    maxCanAccessCount: 5
    rule:
      Sms:
        length: 4
        scope: Number
        extraCharset: ""
      Image:
        length: 4
        scope: Charset
        extraCharset: ""
    app:
      demo1:
        debug: false
        serviceTokenTimeOut: 300000
        maxCanAccessCount: 5
        rule:
          Sms:
            length: 4
            scope: Number
            extraCharset: ""
          Image:
            length: 4
            scope: Charset
            extraCharset: ""