eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 192.168.0.10:${server.port} #实例id
    ip-address: 192.168.0.10 #可访问的ip地址



spring:
  data:
    mongodb:
      database: test
      host: 172.24.246.153:27017
      username: test
      password: test