#设置可访问的ip
eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 127.0.0.1:8400 #实例id
    ip-address: 127.0.0.1 #可访问的ip地址



spring:
  data:
    mongodb:
      database: fcenter
      host: 127.0.0.1:27017

