#设置可访问的ip
eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 192.168.0.255:8400 #实例id
    ip-address: 192.168.0.255 #可访问的ip地址



spring:
  data:
    mongodb:
      database: fcenter
      host: 192.168.8.12:27017
      username: fcenter
      password: fcenter_ayhm_2018
