spring:
  cloud:
    #kafka
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
    #配置中心
    config:
      server:
        git:
          uri: https://github.com/lianshufeng/Fast.git
          search-paths: centers/ApplicationCenter/ConfigServer/src/main/resources/config/**
          force-pull: true
#          username:
#          password:


#注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://127.0.0.1:${ApplicationCenter.port}/eureka/"