#Web服务器端口
server:
  port: ${ConfigCenter.port}


#注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${ApplicationCenter.url}
  instance:
    lease-renewal-interval-in-seconds: 30 # 续约更新时间间隔
    lease-expiration-duration-in-seconds: 90 # 续约到期时间


#允许消息总线
spring:
  cloud:
    #kafka
    stream:
      kafka:
        binder:
          brokers: ${Kafka.brokers}
    bus:
      enabled: true

#允许端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


#调试或者输出日志
logging:
  file: logs/${project.artifactId}.log
#debug: true