#Web服务器端口
server:
  port: ${ConfigCenter.port}


#注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${ApplicationCenter.url}
    healthcheck:
      enabled: true


#允许消息总线
spring:
  cloud:
    #kafka
    stream:
      kafka:
        binder:
          brokers: ${Kafka.brokers}
    bus:
      enabled: true

#允许端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh