spring:
  cloud:
    #配置中心
    config:
      server:
        git:
          uri: http://192.168.8.9:3000/lianshufeng/BaseFast.git
          search-paths: centers/ApplicationCenter/ConfigServer/src/main/resources/config/**
          force-pull: true
          username: aiyihema
          password: aiyihema