eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 192.168.8.51:${ConfigCenter.port} #实例id
    ip-address: 192.168.8.51 #可访问的ip地址

spring:
  cloud:
    #配置中心
    config:
      server:
        git:
          uri: http://222.180.202.110:4000/lianshufeng/BaseFast.git
          search-paths: centers/ApplicationCenter/ConfigServer/src/main/resources/config/**
          force-pull: true
          username: aiyihema
          password: aiyihema