spring:
  cloud:
    #配置中心
    config:
      server:
        git:
          uri: https://github.com/lianshufeng/Fast.git
          search-paths: centers/ApplicationCenter/ConfigServer/src/main/resources/config/**
          force-pull: true
#          username:
#          password:


eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 172.16.134.186:8000 #实例id
    ip-address: 172.16.134.186 #可访问的ip地址