eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 192.168.0.178:${ConfigCenter.port} #实例id
    ip-address: 192.168.0.178 #可访问的ip地址

spring:
  cloud:
    #配置中心
    config:
      server:
        git:
          uri: https://github.com/lianshufeng/Fast.git
          search-paths: centers/ApplicationCenter/ConfigServer/src/main/resources/config/**
          force-pull: true
          username:
          password: