spring:
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
  main:
    allow-bean-definition-overriding: true
server:
  port: ${MonitorServer.port}
zipkin:
  storage:
    elasticsearch:
      cluster: elasticsearch
      hosts: 127.0.0.1:9200
      index: zipkin
    type: elasticsearch
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    web:
      server:
        auto-time-requests: false
