turbine:
  appConfig: userserver,applicationclient
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092