#设置可访问的ip
eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    #    instance-id: 192.168.8.51:${server.port} #实例id
    #    ip-address: 192.168.8.51 #可访问的ip地址
#    instance-id: 192.168.0.10:${server.port} #实例id
#    ip-address: 192.168.0.10 #可访问的ip地址
    instance-id: 192.168.0.31:${server.port} #实例id
    ip-address: 192.168.0.31 #可访问的ip地址



spring:
  data:
    mongodb:
      uri: mongodb://openapi:openapi@192.168.8.52:27017,192.168.8.52:27018,192.168.8.52:27019,192.168.8.52:27020/openapi?replicaSet=MongoSets
      auto-index-creation: true



#debug: true
#logging:
#  level:
#    com:
#      fast:
#        dev:
#          auth:
#            security: DEBUG
#    org:
#      springframework:
#        web:
#          servlet:
#            DispatcherServlet: DEBUG
#        cloud:
#          sleuth: DEBUG
#trace: true
openapi:
  max-time-invalid: 3600000

