#默认端口号
server:
  port: 8080

#  应用中心的地址
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://127.0.0.1:${ApplicationCenter.port}/eureka/"
    healthcheck:
      enabled: true


#允许端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"




#开启断路器
#feign.hystrix.enabled=true




