#默认端口号
server:
  port: 8080

#注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${ApplicationCenter.url}
  instance:
    lease-renewal-interval-in-seconds: 30 # 续约更新时间间隔
    lease-expiration-duration-in-seconds: 90 # 续约到期时间

#设置可访问的ip，一般谁会到具体的环境里
#eureka:
#  instance:
#    prefer-ip-address: true #注册使用ip
#    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例id
#    ip-address: 127.0.0.1 #可访问的ip地址


#允许消息总线
spring:
  cloud:
    #kafka
    stream:
      kafka:
        binder:
          brokers: ${Kafka.brokers}
          replication-factor: 1
    bus:
      enabled: true
  #配置zipkin链路追踪客户端
  zipkin:
    base-url: ${Zipkin.baseUrl}
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: ${Zipkin.sampler.probability}


#允许端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"




#开启断路器
#feign.hystrix.enabled=true




#调试或者输出日志
logging:
  file: 
    name: logs/${project.artifactId}.log
#  level:
#    org:
#      springframework:
#        cloud:
#          sleuth: DEBUG
#        web:
#          servlet:
#            DispatcherServlet: DEBUG

#debug: true