
#设置可访问的ip
eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 192.168.8.51:${server.port} #实例id
    ip-address: 192.168.8.51 #可访问的ip地址



spring:
  activemq:
    broker-url: failover:(tcp://192.168.8.52:61616?connectionTimeout=1000,tcp://192.168.8.52:61626?connectionTimeout=1000,tcp://192.168.8.52:61636?connectionTimeout=1000)?timeout=3000
    #用户名
    user: admin
    #密码
    password: password
  redis:
    host: 192.168.8.52
    port: 6379
    database: 4


mq:
  outerHosts: "mqtt.aiyilearning.com:61614,mqtt.aiyilearning.com:61624,mqtt.aiyilearning.com:61634"






#debug: true
#logging:
#  level:
#    org:
#      apache:
#        activemq: DEBUG
