zuul:
 ribbon.eager-load.enabled: true
 retryable: true #是否开启重试，默认全部都重试
 add-host-header: true
# ignoredServices: "*"
 ignoredPatterns: "/ucenter/manager/**,/userserver/manager/**"
 routes:
#  用户中心
  ucenter:
   stripPrefix: true #是否去掉代理的path前缀
   path: /ucenter/**
   serviceId: UserServer