zuul:
 ribbon.eager-load.enabled: true
 retryable: true #是否开启重试，默认全部都重试
 add-host-header: true
# ignoredPatterns: "/**/manager/**"
 routes:
#  用户中心
  ucenter:
   stripPrefix: false #是否去掉代理的path前缀
   path: /ucenter/**
   serviceId: UserServer
  #例子
  demo:
   stripPrefix: false
   path: /demo/**
   serviceId: demo