zuul:
 ribbon.eager-load.enabled: true
 retryable: true #是否开启重试，默认全部都重试, 特殊的在 yxz-zuul-filter.yml 中配置
 add-host-header: true
 routes:
  #用户中心
  ucenter:
   stripPrefix: true #是否去掉代理的path前缀
   path: /**
   serviceId: UserServer
  #例子
  demo:
   stripPrefix: false
   path: /demo/**
   serviceId: demo