eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 172.16.134.184:${GetWayCenter.port.port} #实例id
    ip-address: 172.16.134.184 #可访问的ip地址


#开启断路器
#feign.hystrix.enabled=true


#retry
#该参数用来开启重试机制=true
#断路器的超时时间,断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

