#默认端口号
server:
  port: 8080

#注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${ApplicationCenter.url}


#允许消息总线
spring:
  cloud:
    #kafka
    stream:
      kafka:
        binder:
          brokers: ${Kafka.brokers}
    bus:
      enabled: true


#权限配置
usersecurity:
  #默认不使用角色前缀
  rolePrefixName: ""
  needSecurityMethodUrl: "/**/*"
  excludeSecurityMethodUrl: "/resources/**,/error"




#允许端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"




#使用断路器
feign:
  hystrix:
    enabled: true

