#设置可访问的ip
eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 127.0.0.1:8100 #实例id
    ip-address: 127.0.0.1 #可访问的ip地址



spring:
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
  data:
    mongodb:
      database: ulocal
      host: 127.0.0.1:27017
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1



#配置
kaptcha:
  width: 100
  height: 41
  fontColor: "red"
  fontNames: "宋体,楷体,微软雅黑"


ucenter:
  validate:
    #全局配置
    debug: true
    serviceTokenTimeOut: 300000
    maxCanAccessCount: 5
    rule:
      Mail:
        length: 8
        scope: Number
        extraCharset: ""
        templateId: "uCenterMail"
      Sms:
        length: 4
        scope: Number
        extraCharset: ""
        templateId: "uCenterSms"
      Image:
        length: 4
        scope: Charset
        extraCharset: ""
    app:
      demo1:
        debug: false
        rule:
          Sms:
            length: 4
            scope: Number
            template:
              Fast: "UserFastLogin"
              Login: "UserLogin"
              Register: "UserRegister"
              UpdatePassWord: "UserUpdatePassWord"
          Mail:
            template:
              Fast: "UserFastLogin"
              Login: "UserLogin"
              Register: "UserRegister"
              UpdatePassWord: "UserUpdatePassWord"