spring:
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
  data:
    mongodb:
      database: udev
      host: 127.0.0.1:27017
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
#用户中心配置
ucenter:
  phoneValidataLength: 4
  imageValidataLength: 4
  debug: true



