spring: 
 #thymeleaf
 thymeleaf:
  #开发阶段取消缓存
  cache: false
# rabbitmq:
#  host: 127.0.0.1
#  port: 5672
  #username=
  #password=
  #kafka
 cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092

#mongodb
fast:
 mongodb:
  dbName: udev
  host: 127.0.0.1:27017


