#设置可访问的ip
eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 172.16.134.186:8100 #实例id
    ip-address: 172.16.134.186 #可访问的ip地址



spring:
  #thymeleaf
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    #开发阶段取消缓存
    cache: false
    encoding: UTF-8
  #mongodb
  data:
    mongodb:
      database: ucenter
      host: 172.16.119.142:27017
#      username:
#      password:
  redis:
    host: 172.16.134.183
    port: 6379
    database: 1


#验证码图片配置
kaptcha:
  width: 100
  height: 41
  fontColor: "blue"
  fontNames: "宋体,楷体,微软雅黑"


ucenter:
  validate:
    #全局配置
    debug: false
    serviceTokenTimeOut: 300000
    maxCanAccessCount: 5
    rule:
      Sms:
        length: 4
        scope: Number
        extraCharset: ""
        template:
          Fast: SMS_88888 #验证码${code}，您正在进行身份验证，打死不要告诉别人哦！
          Login: SMS_88888 #验证码${code}，您正在登录，若非本人操作，请勿泄露。
          Register: SMS_88888 #验证码${code}，您正在注册成为新用户，感谢您的支持！
          UpdatePassWord: SMS_88888 #验证码${code}，您正在尝试修改登录密码，请妥善保管账户信息。
      Image:
        length: 4
        scope: Charset
        extraCharset: ""
    app:
      teachermanager:
        debug: true
        serviceTokenTimeOut: 300000
        maxCanAccessCount: 5
        rule:
          Sms:
            length: 4
            scope: Number
            extraCharset: ""
          Image:
            length: 4
            scope: Charset
            extraCharset: ""