spring:
  #thymeleaf
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    #开发阶段取消缓存
    cache: false
    encoding: UTF-8
  #mongodb
  data:
    mongodb:
      database: uprod
      host: 127.0.0.1:27017
        #     username:
        #     password:


server:
  port: ${UserCenter.port}
  servlet:
    context-path: ${UserCenter.context.path}





