#thymeleaf 模版引擎
spring:
 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8
  #开发阶段取消缓存
  cache: false

#mongodb
fast:
 mongodb:
  dbName: udev
  host: 127.0.0.1:27017

#rabbitmq
spring:
 rabbitmq:
  host: 127.0.0.1
  port: 5672
  #username=
  #password=