spring:
  #thymeleaf
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    #开发阶段取消缓存
    cache: false
    encoding: UTF-8
  #mongodb
  data:
    mongodb:
      database: utest
      host: 127.0.0.1:27017
    #     username:
    #     password:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1

#用户中心配置
ucenter:
  phoneValidateLength: 4
  debug: false
  imageValidateLength: 4
  serviceTokenTimeOut: 300000
  maxCanAccessCount: 5


#验证码图片配置
kaptcha:
  width: 100
  height: 41
  fontColor: "blue"
  fontNames: "宋体,楷体,微软雅黑"