spring: 
 #thymeleaf
 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8
  #开发阶段取消缓存
  cache: true
 #rabbitmq
 rabbitmq:
  host: 127.0.0.1
  port: 5672
  #username=
  #password=


#mongodb
fast:
 mongodb:
  dbName: utest
  host: 127.0.0.1:27017

