spring: 
 #thymeleaf
 thymeleaf:
  suffix: .html
  mode: HTML
  prefix: classpath:/templates/
  #开发阶段取消缓存
  cache: false
  encoding: UTF-8
 #mongodb
 data:
   mongodb:
     database: utest
     host: 127.0.0.1
     port: 27017

