spring:
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
  data:
    mongodb:
      database: udev
      host: 127.0.0.1:27017
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
#用户中心配置
ucenter:
  phoneValidataLength: 4
  phoneValidataDebug: true
  imageValidataLength: 4


#配置
kaptcha:
  width: 100
  height: 41
  fontColor: "red"
  fontNames: "宋体,楷体,微软雅黑"

