#用户令牌的缓存配置
tokencache:
  timeToLiveSeconds: 600
  timeToIdleSeconds: 60
  maxMemoryCount: 1000
  overflowToDisk: false

usersecurity:
  rolePrefixName: "ROLE_"
  needSecurityMethodUrl: "/**/*"
  excludeSecurityMethodUrl: "/resources/**,/error"

#使用断路器
fegin:
  hystrix:
    enabled: true


#允许消息总线
spring:
  cloud:
    stream:
      bindings:
        UserCenterInputStream:
          group: null
        UserCenterOuputStream:
          group: "UserCenterStream"
          destination: "UserCenterInputStream"
      #kafka
      kafka:
        binder:
          brokers: ${Kafka.brokers}
    bus:
      enabled: true


logging:
  level:
    com.fast.dev.ucenter.security: DEBUG