#设置可访问的ip
eureka:
  instance:
    prefer-ip-address: true #注册使用ip
    instance-id: 192.168.8.51:${server.port} #实例id
    ip-address: 192.168.8.51 #可访问的ip地址



spring:
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
  data:
    mongodb:
      uri: mongodb://robotfirewall:robotfirewall_ayhm_2019@192.168.8.52:27017,192.168.8.52:27018,192.168.8.52:27019,192.168.8.52:27020/robotfirewall?replicaSet=MongoSets
      auto-index-creation: true
#      database: robotfirewall
#      host: 192.168.8.52:27017
#      username: robotfirewall
#      password: robotfirewall_ayhm_2019



